### ISSUE TITLE
how to use cachix? typical build commands?

### ISSUE THREAD

**Issue by dckc** [DLR-FT/seL4-nix-utils#25]
This looks really cool (I found it via the [Summit abstracts](https://sel4.systems/Foundation/Summit/2024/abstracts2024)), but I'm struggling a bit trying to figure out which end is up. Here's hoping you have some free time to answer some remedial nix questions. I completely understand if not...

Based on ci logs, I tried cloning at e6c03d0 and then:

```console
$ cachix use dlr-ft
Configured https://dlr-ft.cachix.org binary cache in /home/connolly/.config/nix/nix.conf

$ nix build .#packages.x86_64-linux.atf-aarch64-zcu102
[1/1/3 built, 25 copied (497.4/497.5 MiB), 104.8 MiB DL] building openssl-aarch64-unknown-linux-gnu-3.0.13 (buildPhase): aarch64-unknown-linux-gnu-error: interrupted by the user
```

I interrupted it because I expected to get cache hits for everything. I don't understand why any local builds are happening.

Likewise, `nix build .#seL4-kernel-x64` starts building binutils.

`nix build .#seL4-deps` seems to be a noop... I guess that's because I did `direnv enable` and the deps were grabbed at that point.

What are the target packages that you typically use? Each ci build seems to do about 20 of them. It would be nice if the README told a little about what a few of those do.

`nix flake show` lists a whole bunch of stuff, but I'm not even sure which parts of it to pick out to feed to `nix build`. I guess it's starting to make sense...

**Comment by wucke13** [comment]
> This looks really cool (I found it via the [Summit abstracts](https://sel4.systems/Foundation/Summit/2024/abstracts2024)), but I'm struggling a bit trying to figure out which end is up.

I'm glad to hear that it looks cool, and I'm sorry that you struggle a little.

> Here's hoping you have some free time to answer some remedial nix questions. I completely understand if not...

Of course!

> I interrupted it because I expected to get cache hits for everything. I don't understand why any local builds are happening.

The derivations are too big, i.e., this cachix gets evicted too often. I'm afraid, I will not be able to provide a simple, affordable binary cache for this stuff in the near future, but I'm not giving up on it. In the end, for now, this boils down to: you will have to compile for some 15-30 minutes (on a powerful machine that is). I fully understand that this is sub-optimal.

To be fair, I do not promote the cachix as something you can use, at the moment it is just an implementation detail of our CI pipeline. Again I do fully understand that it would be valuable to have it accessible and actually working for all users.

> `nix build .#seL4-deps` seems to be a noop... I guess that's because I did direnv enable and the deps were grabbed at that point.

Exactly!

> What are the target packages that you typically use? Each ci build seems to do about 20 of them. It would be nice if the README told a little about what a few of those do.

We mostly use the microkit-sdk devShell, and the associated development environment for seL4-kernel. I think I will link the slides for the presentation at the seL4 summit from the readme some time after next week, those contain some examples. On second thought, it makes sense to put a copy-pasteable example usage to the readme, convenience is key. Opened #26 for that purpose.

To be more specific: 

- `nix develop .\#microkit` drops you in a devshell that has all the things available to play the [microkit tutorial](https://trustworthy.systems/projects/microkit/tutorial/)
- `nix build .\#seL4-test-armv7l-zynq7000-simulate` for example builds the tests, which is nice to actually see something in action. After the build, one can `cd result && ./simulate`.
- `nix develop .\#seL4-camkes-vm-examples-aarch64-qemu-arm-virt` should put you into devShell that has everything to tinker with the camkes-vm-example, i.e. building virtual machines on top of seL4. Unfortunately, due to not having that stuff in cache, I can not easily verify right now :rofl:. If it actually works, you should be able to call the following commands to compile the example (and you can change source and repeat at any time to also change the results):

```
nix develop .\#seL4-camkes-vm-examples-aarch64-qemu-arm-virt
unpackPhase
cd source
configurePhase
buildPhase
```

You can also use directly the camek/`init-build.sh` stuff, but then you might have to figure out the right flags for it work as well.


In any case, please feel free to talke to me at the summit and bring forward any questions, I'm happy to do hands-on and I'll do my best to answer all your questions!

I will leave this issue open, until when I can present a decent caching mechanism.

**Comment by wucke13** [comment]
@dckc Hi, I reorganized some of the Cachix infrastructure, and there is now a better chance of not having our seL4 stuff evicted. Please feel free to let some feedback over at https://github.com/DLR-FT/seL4-nix-utils/pull/30 . I will likely merge that some time in the upcoming days.

**Comment by dckc** [comment]
Thanks for all the info!

The "We mostly use ..." and "To be more specific ..." stuff is just what I was looking for. Please consider adding some version of that to the README.

**Comment by wucke13** [comment]
@dckc I merged the PR, now also with a more comprehensive "Getting Started" section. Thus, I'm closing the issue. Feel free to re-open if you think there is more to do :smile:
